### PR TITLE
fix(project): prevent autocomplete options from being uncollapsed ini…

### LINKED ISSUE #51: Autocomplete is initially uncollapsed when items are supplied
When an autocomplete is supplied with items and with an initial selection, the items matching the initial selection are uncollapsed after the component is created because `hasFocues` is set to `true` in `valueChanged()`.
```html
<auto-complete result.bind="mySelection" items.bind="myOptions"></auto-complete>
```

### PR DESCRIPTION
**Pull request by Mobe91**
Fixes #51

### CODE REVIEW

File: src/component/autocomplete.js [hunk 1]
```diff
@@ -276,9 +276,10 @@ export class AutoCompleteCustomElement {
    * @returns {Promise}
    */
   valueChanged() {
+    let initial = this.initial;
     if (!this.shouldPerformRequest()) {
```
Comment (RWOverdijk) [inline src/component/autocomplete.js]: Newline between if and let.

**Review by RWOverdijk — CHANGES_REQUESTED** [review]

**Comment by Mobe91** [comment]
@RWOverdijk Are there any other changes required for this PR?

**Comment by RWOverdijk** [comment]
I should test this but I'm quite overwhelmed with work. I;'ll push this onto the prerelease as well, and create a new issue to collect feedback.
